"""Updated table submitted

Revision ID: 33c77a959c24
Revises: f4e810c735c3
Create Date: 2024-02-07 17:24:36.708307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33c77a959c24'
down_revision = 'f4e810c735c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submitted_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_graded', sa.Boolean(), nullable=True))
        batch_op.alter_column('grade',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submitted_assignments', schema=None) as batch_op:
        batch_op.alter_column('grade',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('is_graded')

    # ### end Alembic commands ###
