"""image row added for users

Revision ID: d306e884b9c1
Revises: ec2cee751578
Create Date: 2024-01-14 21:49:53.678496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd306e884b9c1'
down_revision = 'ec2cee751578'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imageUrl', sa.NVARCHAR(), nullable=True))

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imageUrl', sa.NVARCHAR(), nullable=True))

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imageUrl', sa.NVARCHAR(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_column('imageUrl')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('imageUrl')

    with op.batch_alter_table('parents', schema=None) as batch_op:
        batch_op.drop_column('imageUrl')

    # ### end Alembic commands ###
